general-pro:
  prop-1:  prop-1-pro-value
  prop-2:  prop-2-pro-value
general-int:
  prop-3:  prop-3-int-value
  prop-4:  prop-4-int-value
  prop-5:  prop-5-int-value
common:
  prop-6: prop-6-common-value
app-pro:
  prop-1: prop-1-app-pro-value
  prop-7: prop-7-app-pro-value
app-int:
  prop-3: prop-3-app-value
  prop-8: prop-8-app-value


properties:
  prop-1: prop-1-app-pro-value
  prop-2: prop-2-pro-value
  prop-3: prop-3-app-value
  prop-4: prop-4-int-value
  prop-5: prop-5-int-value
  prop-6: prop-6-common-value
  prop-7: prop-7-app-pro-value
  prop-8: prop-8-app-value